### ISSUE TITLE
Program should prompt the user 

### ISSUE THREAD

**Issue by EremitaV** [mikepound/pwned-search#35]
Isn't it a bit worrying that the password is stored in plaintext in the terminal history?

**Comment by mikepound** [comment]
I can't speak for the other language implementations, as I only contributed to the python version. This issue is only true when passing a password directly, which is in some sense a "legacy" way of using this python script, a warning is supplied on this in the readme. If you simply call then python script, it will read stdin within the process and no history will be saved.

I agree that passing in passwords via the command line is not the best way to use the code. I decided not to remove it simply for ease of use if people want to, it depends what threat model people are worried about.

**Comment by simdimdim** [comment]
@mikepound first and foremost, great vid, didn't know that site existed.
as for the issue and script I'd opt in for
```python
import getpass
...
sha1pwd=hashlib.sha1(getpass.getpass().encode("utf-8")).hexdigest().upper()
```
